### ISSUE TITLE
[Bug] Link in heading expands full width

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/appflowy-editor#357]
### Bug Description

If a link is the last thing in a heading block, then it expands the full width, and clicking on the whitespace to the right of it is the same as clicking the link.

### How to Reproduce

- Insert any heading (h1, h2, or h3)
- Write some text
- Select that last word in the text
- Insert link

### Expected Behavior

Only the link itself is clickable.

### Operating System

MacOS, Windows

### AppFlowy Editor Version(s)

main

**Comment by zoli** [comment]
I just wanted to note the attempt to resolve this problem with [this commit](https://github.com/AppFlowy-IO/appflowy-editor/commit/4ccd811cdae46bb0509ce9122d92b647692b621e) prevents the heading moving to the right side of the page in RTL direction.
I have to write some tests for moving to the right side case so that in the future we get aware when some change breaks it.

**Comment by zoli** [comment]
Also, I'm not sure how both of these problems could get solved together.

**Comment by zoli** [comment]
I think this is fixed now and this issue can get cloesd.
