### ISSUE TITLE
[Bug] Copy Paste in Editor showing unusual behaviour when the portion copied has text color or highlight color

### ISSUE THREAD

**Issue by Mukund-Tandon** [AppFlowy-IO/appflowy-editor#388]
### Bug Description

https://forum.appflowy.io/t/copy-paste-in-editor-showing-unusual-behaviour-when-the-portion-copied-has-text-color-or-highlight-color/55

![ezgif com-video-to-gif (1)](https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/5bb04b95-5a02-474e-848a-ffab25b9cbc3)
![ezgif com-video-to-gif](https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/8c5f0cac-981c-45d6-8561-343f0933a0f3)
In above two Gifs we can see that copy paste show some unusual behaviour , if the text copied has a text color or highlight

### How to Reproduce

As in above two GIFs 
- copy a text with text color and highlight
- paste it 
- It should show this unusual behaviour 

### Expected Behavior

the text pasted should be exactly same as the text copied

### Operating System

MacOs

### AppFlowy Editor Version(s)

1.2.3

**Comment by LucasXu0** [comment]
I have re-implemented the copy/paste/cut feature in AppFlowy and will be transferring the corresponding logic into the editor-plugin repository instead of the editor repository. I am opting not to import it directly into the editor repository because the new feature relies on the Rust code.

https://github.com/AppFlowy-IO/AppFlowy/pull/3233
