### ISSUE TITLE
[FR] Add the rules to analysis_options.yaml based on AppFlowy Flutter Style Guide

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/appflowy-editor#56]
### Description

We should add rules to `analysis_options.ymal`, located in `frontend/analysis_options.yaml`, based on [AppFlowy Flutter Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)

- [x] #57

### Impact

This will help format the code and reduce the time required for code reviewing.

#### Reference
* https://dart-lang.github.io/linter/lints/index.html
* https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides

**Please DO NOT close this issue**. We will keep this issue open to continue discussing which rules should be added.

**Comment by Xazin** [comment]
I can work on this.

I have one question though, according to the style guide, we should declare the type for all variables. There is a lint for this: https://dart-lang.github.io/linter/lints/always_specify_types.html

I want to know your opinion on this specific lint before I add it, since it's quite a lot of work.

**Comment by Xazin** [comment]
I'll do a PR for the rest of the lints once most of the PRs are merged, such that there is less work in rebasing.
