### ISSUE TITLE
[Question] Why use delta in document json?

### ISSUE THREAD

**Issue by tilemoon** [AppFlowy-IO/appflowy-editor#86]
```dart
  final document = {
    "document": {
      "type": "editor",
      "children": [
        {
          "type": "text",
          "delta": [
            {
              "insert": "AppflowyEditor",
            }
          ]
        },
      ]
    }
  };
```
why not just like this:

```dart
  final document = {
    "document": {
      "type": "editor",
      "children": [
        {
          "type": "text",
          "text": "AppflowyEditor",
        },
      ]
    }
  };
```

can someone tell me why?

**Comment by LucasXu0** [comment]
@tilemoon There's two main reasons.

1. The `delta` is ready for collaboration. https://quilljs.com/docs/delta/
2. Customizing the style becomes easier when not using plain text, as it can be difficult to customize the style for each text otherwise.
<img width="516" alt="Screenshot 2023-04-20 at 13 57 29" src="https://user-images.githubusercontent.com/11863087/233271565-f5736741-5cc8-4792-9e15-e4f32c1e3d52.png">
